
title: Hiroaki Fujita's Website
email: fujita.hiroaki.3x@kyoto-u.ac.jp
domain: hiroakifujita
baseurl: ""
url: https://hiroakifujita 
github_username:  hiroakif93

# Build settings
theme: minima
plugins:
  - jekyll-sitemap

include:
  - _contents
  - _assets
  - _publications