
title: Hiroaki Fujita's Website
email: fujita.hiroaki.3x@kyoto-u.ac.jp
domain: hiroakif93.github.io

github_username:  hiroakif93

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
sass:
  sass_dir: _sass
  style: compressed

include:
  - _contents
  - _contents/about
  - _contents/publications
  
affiliation:
  - Graduate School of Biostudies,
  - Center for Living Systems Information Science (CeLiSIS),
  - Kyoto University.
 