
title: Hiroaki Fujita's Website
email: fujita.hiroaki.3x@kyoto-u.ac.jp
domain: hiroakif93.github.io
baseurl: ""
url: https://hiroakif93.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hiroakif93

# Build settings
theme: minima
plugins:
  - jekyll-sitemap

include:
  - _contents
  - _assets
  - _publications