
title: Hiroaki Fujita's Website
email: fujita.hiroaki.3x@kyoto-u.ac.jp
domain: hiroakif93.github.io
baseurl: ""
url: "" 
github_username:  hiroakif93

# Build settings
theme: minima
plugins:
  - jekyll-sitemap

include:
  - _contents
  - _assets
  - _publications

affiliation:
  - Graduate School of Biostudies,
  - Center for Living Systems Information Science (CeLiSIS),
  - Kyoto University.

sidebar:
  position: left
  display: post
  - R
    